sources:
  - name: Books
    handler:
      openapi:
        source: http://localhost:3002/openapi.json
  - name: Authors
    handler:
      jsonSchema:
        endpoint: http://localhost:3003
        operationHeaders:
          content-type: application/json
        operations:
         - type: Mutation
           field: authors
           path: /authors
           method: POST
           requestSample: ./request.json
           responseSample: ./users.json
         - type: Query
           field: author
           path: /author/{args.id}
           method: GET
           responseSample: ./user.json
  - name: Stores
    handler:
      graphql:
        endpoint: http://0.0.0.0:3004/graphql
