plugins:
  - httpDetailsExtensions:
      {}
sources:
  - name: Books
    handler:
      openapi:
        source: http://localhost:3002/openapi/spec.yaml
  - name: Authors
    handler:
      jsonSchema:
        endpoint: http://localhost:3003
        operationHeaders:
          content-type: application/json
        operations:
         - type: Query
           field: authors
           path: /authors
           method: GET
           responseSample: ./users.json
           argTypeMap:
              ids:
                type: array
                items:
                  type: string
           queryParamArgMap:
              ids[]: ids
         - type: Query
           field: author
           path: /author/{args.id}
           method: GET
           responseSample: ./user.json
  - name: Stores
    handler:
      graphql:
        endpoint: http://0.0.0.0:3004/graphql
transforms:
  - filterSchema:
      filters:
        - Query.{stores, authors, books}
        - Mutation.!*

additionalTypeDefs: |
  extend type Store {
    bookSells: [Sells!]! @resolveTo(
      sourceName: "Stores",
      sourceTypeName: "Query",
      sourceFieldName: "bookSells",
      requiredSelectionSet: "{ id }",
      sourceArgs: {
        storeId: "{root.id}"
      }
    )
  }
  extend type Sells {
    book: Book @resolveTo(
      sourceName: "Books",
      sourceTypeName: "Query",
      sourceFieldName: "books",
      requiredSelectionSet: "{ bookId }",
      keysArg: "ids_LEFT_SQUARE_BRACE__RIGHT_SQUARE_BRACE_"
      keyField: "bookId"
    )
  }
  extend type Book {
    author: query_author @resolveTo(
      sourceName: "Authors"                                  
      sourceTypeName: "Query",       
      sourceFieldName: "authors",
      requiredSelectionSet: "{ authorId }",
      keysArg: "ids"
      keyField: "authorId"
    )
  }
# additionalResolvers:
#   - targetTypeName: Store
#     targetFieldName: bookSells
#     sourceName: Stores # Which source does the target field belong to?
#     sourceTypeName: Query # Which root type does the target field belong to?
#     sourceFieldName: bookSells # What is the source field name?
#     requiredSelectionSet:
#       |
#       {
#         id
#       }
#     sourceArgs: # What args does this need to take?
#       storeId: "{root.id}"
#   - targetTypeName: Sells
#     targetFieldName: book
#     sourceName: Books # Which source does the target field belong to?
#     sourceTypeName: Query # Which root type does the target field belong to?
#     sourceFieldName: book # What is the source field name?
#     requiredSelectionSet:
#       |
#       {
#         bookId
#       }
#     sourceArgs: # What args does this need to take?
#       id: "{root.bookId}"
#   - targetTypeName: Book
#     targetFieldName: author
#     sourceName: Authors # Which source does the target field belong to?
#     sourceTypeName: Mutation # Which root type does the target field belong to?
#     sourceFieldName: authors # What is the source field name?
#     requiredSelectionSet:
#       |
#       {
#         authorId
#       }
#     keysArg: "input.ids"
#     keyField: "authorId"

